import type { Metadata } from 'next'
import '../styles/globals.css'
import { Navigation } from '../components/Navigation';
import { font } from './fonts'

export const metadata: Metadata = {
  title: 'Experimental Next',
  description: 'Generated by Federico J.B',
}

export default function RootLayout({ children}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
        <head>
          <title>ExperiNext con Next.js</title>
        </head>
        <body className={font.variable}>
          <Navigation />
          {children}
        </body>
    </html>
  )
}
